"""CV entity updated

Revision ID: 2d7f7e8fa1a3
Revises: 86be95a4df0d
Create Date: 2026-02-26 00:20:30.019371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7f7e8fa1a3'
down_revision: Union[str, Sequence[str], None] = '86be95a4df0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cvs', sa.Column('s3_bucket', sa.Text(), nullable=True))
    op.add_column('cvs', sa.Column('original_filename', sa.Text(), nullable=True))
    op.add_column('cvs', sa.Column('content_type', sa.Text(), nullable=True))
    op.add_column('cvs', sa.Column('size_bytes', sa.Integer(), nullable=True))
    op.add_column('cvs', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cvs', 'uploaded_at')
    op.drop_column('cvs', 'size_bytes')
    op.drop_column('cvs', 'content_type')
    op.drop_column('cvs', 'original_filename')
    op.drop_column('cvs', 's3_bucket')
    # ### end Alembic commands ###
