"""Change user id

Revision ID: 39d2fab2ebbe
Revises: 86c2508845a3
Create Date: 2026-02-15 23:36:21.829903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39d2fab2ebbe'
down_revision: Union[str, Sequence[str], None] = '86c2508845a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
     # 1) remove all rows (and dependent rows)
    op.execute("TRUNCATE TABLE users RESTART IDENTITY CASCADE;")

    # 2) drop old PK constraint
    op.drop_constraint("users_pkey", "users", type_="primary")

    # 3) drop old integer id column
    op.drop_column("users", "id")

    # 4) add new uuid id column
    op.add_column(
        "users",
        sa.Column("id", sa.UUID(as_uuid=True), nullable=False)
    )

    # 5) recreate PK
    op.create_primary_key("users_pkey", "users", ["id"])

    # 6) drop old index if it exists (PK already indexes)
    op.drop_index(op.f("ix_users_id"), table_name="users", if_exists=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
