"""auth 0 filed added to user

Revision ID: cc3eaed29f6b
Revises: a1b2c3d4e5f6
Create Date: 2026-02-17 08:29:12.905896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc3eaed29f6b'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('recruiter_organization_userid_fkey'), 'recruiter_organization', type_='foreignkey')
    op.drop_constraint(op.f('recruiter_organization_organizationif_fkey'), 'recruiter_organization', type_='foreignkey')
    op.create_foreign_key(None, 'recruiter_organization', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recruiter_organization', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('auth0_sub', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_users_auth0_sub'), 'users', ['auth0_sub'], unique=True)
    op.drop_constraint(op.f('fk_users_organization_id'), 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=225), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_users_organization_id'), 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_users_auth0_sub'), table_name='users')
    op.drop_column('users', 'auth0_sub')
    op.drop_constraint(None, 'recruiter_organization', type_='foreignkey')
    op.drop_constraint(None, 'recruiter_organization', type_='foreignkey')
    op.create_foreign_key(op.f('recruiter_organization_organizationif_fkey'), 'recruiter_organization', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(op.f('recruiter_organization_userid_fkey'), 'recruiter_organization', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
