"""Create organization table

Revision ID: e5629043858d
Revises: 39d2fab2ebbe
Create Date: 2026-02-15 23:42:21.235536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5629043858d'
down_revision: Union[str, Sequence[str], None] = '39d2fab2ebbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('plan', sa.Enum('free', 'pro', 'enterprise', name='plan_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruiter_organization',
    sa.Column('userid', sa.UUID(), nullable=False),
    sa.Column('organizationif', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organizationif'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('userid', 'organizationif')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recruiter_organization')
    op.drop_table('organizations')
    # ### end Alembic commands ###
