from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, TypedDict


class ParseMetadata(TypedDict):
    """Parse validity fields returned by api-gateway and cv-service ai-context endpoints.

    All fields are nullable because a record that has never been parsed returns
    null for every metadata field.
    """

    parse_version: str | None
    model_version: str | None
    prompt_version: str | None
    content_hash: str | None
    parsed_at: datetime | None


class AgentState(TypedDict):
    """Full state carried through the JD/CV matching LangGraph.

    All keys are always present in the dict. Fields that may not yet have a
    value use `X | None` - LangGraph requires a fixed, serialisable schema for
    checkpointing so optional keys are not used.
    """

    # --- Request metadata ---
    job_id: uuid.UUID
    cv_id: uuid.UUID
    candidate_id: uuid.UUID | None
    request_id: str                    # UUID string generated by load_request_context
    triggered_by: str                  # "api" | "background_job" | "test"

    # --- Raw inputs ---
    jd_raw: str | None                 # raw job description text fetched from api-gateway
    cv_raw: str | None                 # raw extracted CV text fetched from cv-service

    # --- Parsed artefacts ---
    # Stored as dicts (not Pydantic models) so state remains JSON-serialisable
    parsed_jd: dict[str, Any] | None   # ParsedJobDescriptionSchema.model_dump()
    parsed_cv: dict[str, Any] | None   # CVStructuredProfile.model_dump()

    # --- Parse metadata (from ai-context endpoints) ---
    jd_parse_metadata: ParseMetadata | None
    cv_parse_metadata: ParseMetadata | None

    # --- Validity flags set by validate_jd_parse / validate_cv_parse nodes ---
    jd_parse_valid: bool
    cv_parse_valid: bool

    # --- Normalised inputs set by normalize_inputs node ---
    normalized_jd: dict[str, Any] | None
    normalized_cv: dict[str, Any] | None

    # --- Matching output set by run_matching_analysis node ---
    matching_result: dict[str, Any] | None
    match_score: float | None

    # --- Errors ---
    errors: list[str]                  # non-fatal warnings; accumulate across nodes
    fatal_error: str | None            # if set, graph routes to handle_error and aborts

    # --- Execution metadata ---
    steps_taken: list[str]             # node names appended as each node completes
    started_at: datetime
    completed_at: datetime | None
    retry_count: int
